apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/inject: "false"
        # sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        # sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: consul
    spec:
      # nodeName: h2.amd.meshbench-pg0.utah.cloudlab.us
      containers:
        - image: consul:latest
          name: consul
          ports:
            - containerPort: 8300
            - containerPort: 8400
            - containerPort: 8500
            - containerPort: 53
              protocol: UDP
          resources:
            limits:
              cpu: 1000m
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
    workload: hotel
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        #s idecar.istio.io/proxyCPU: "500m"
        # sidecar.istio.io/inject: "false"
        # sidecar.istio.io/userVolumeMount: '[{"name":"log", "mountPath":"/var/log/tap"}]'
        # sidecar.istio.io/userVolume: '[{"name": "log", "emptyDir":{}}]'
        # sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        # sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      # nodeName: h2.amd.meshbench-pg0.utah.cloudlab.us
      containers:
        - command:
            - frontend
          image: xzhu0027/hotel_reserv_frontend_single_node
          name: hotel-reserv-frontend
          ports:
            - containerPort: 5000
          # resources:
          #   limits:
          #     cpu: 1000m
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-user
  name: mongodb-user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-user
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/inject: "false"
        # sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        # sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-user
    spec:
      # nodeName: h2.amd.meshbench-pg0.utah.cloudlab.us
      containers:
        - image: mongo
          name: hotel-reserv-user-mongo
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: 1000m
          volumeMounts:
            - mountPath: /mnt/data/db
              name: user
      hostname: user-db
      restartPolicy: Always
      volumes:
        - name: user
          persistentVolumeClaim:
            claimName: user-pvc
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: user
    workload: hotel
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        # sidecar.istio.io/inject: "false"
        # sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        # sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: user
    spec:
      # nodeName: h2.amd.meshbench-pg0.utah.cloudlab.us
      containers:
        - command:
            - user
          image: xzhu0027/hotel_reserv_user_single_node:test
          name: hotel-reserv-user
          ports:
            - containerPort: 8086
          # resources:
          #  limits:
          #   cpu: 1000m
      restartPolicy: Always
status: {}
---
